#!/usr/bin/php
<?php
/**
 * Plugin Setup Script
 *
 * Copies the contents to a sepcified directory,
 * with all name placeholders taken care of.
 */
chdir( __DIR__ );

$plugin = array();

// Get the plugin name
$plugin['name'] = readline( 'What is your plugin called? ' );
if ( ! $plugin['name'] ) {
	die( "No plugin name provided.\n" );
}

// Get optional description/tags
$plugin['desc'] = readline( 'What does it do in a nutshell? ' );
$plugin['tags'] = readline( 'What should it be tagged as? ' );

// Guess the filename
$plugin['file'] = strtolower( preg_replace( '/[\W_]+/', '-', $plugin['name'] ) );

// Guess the Namespace
$plugin['ns'] = preg_replace( '/\W+/', '', $plugin['name'] );

// Guess the slug
if ( strpos( ' ', $plugin['name'] ) ) {
	$plugin['slug'] = preg_replace( '/([A-Z])\w+( |$)/', '$1', strtoupper( $plugin['name'] ) );
} else {
	$plugin['slug'] = strtoupper( substr( $plugin['name'], 0, 2 ) );
}

// Offer to override the filename
if ( $value = readline( "Override assumed directory/file name ({$plugin['file']})? " ) ) {
	$plugin['file'] = $value;
}

// Offer to override the namespace
if ( $value = readline( "Override assumed namespace ({$plugin['ns']})? " ) ) {
	$plugin['ns'] = $value;
}

// Offer to override the slug
if ( $value = readline( "Override assumed slug ({$plugin['slug']})? " ) ) {
	$plugin['slug'] = $value;
}

// Get the plugin directory
$plugin['dir'] = readline( "Where should your plugin be? Leave blank for this boilerplate's parent directory (" . dirname( __DIR__ ) . "): " );
if ( ! $plugin['dir'] ) {
	$plugin['dir'] = '../';
}

// Calculate real path
$plugin['dir'] = realpath( $plugin['dir'] );

function rename_files( $dir ) {
	global $plugin;

	$files = scandir( $dir );
	foreach ( $files as $file ) {
		if ( substr( $file, 0, 1 ) == '.' || in_array( $file, array( 'build', 'README.md' ) ) ) {
			continue;
		}

		if ( is_dir( $file ) ) {
			rename_files( "$dir/$file" );
		} else {
			$content = file_get_contents( "$dir/$file" );
			$content = str_replace( array(
				'[plugin name]',
				'[plugin description]',
				'[plugin tags]',
				'PluginName',
				'pluginname',
				'plugin-name',
				'SLUG',
			), array(
				$plugin['name'],
				$plugin['desc'],
				$plugin['tags'],
				$plugin['ns'],
				strtolower( $plugin['ns'] ),
				$plugin['file'],
				$plugin['slug']
			), $content );

			$destination = $plugin['dir'] . '/' . $plugin['file'] . str_replace(
				array( 'plugin-name', 'pluginname' ),
				array( $plugin['file'], strtolower( $plugin['ns'] ) ),
				substr( "$dir/$file", strlen( __DIR__ ) )
			);

			if ( ! file_exists( dirname( $destination ) ) ) {
				mkdir( dirname( $destination ), 0777, true );
			}
			file_put_contents( $destination, $content );
		}
	}
}

rename_files( dirname( __FILE__ ) );